name: gh-pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.0.0
          cache: yarn
      - run: yarn install
      - run: |
          set -eux
          yarn build
          touch public/.nojekyll
        env:
          ALGOLIA_APP_ID: N8H0FCYD7M
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          ALGOLIA_SEARCH_API_KEY: bf4822cb6b0577a3dd593af29478fa8f
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          allow_empty_commit: false
