name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.6.2
          cache: yarn
      - run: yarn install
      - run: yarn test
      - run: yarn lint
