name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: yarn
      - run: yarn install
      - run: yarn test
      - run: yarn lint
